run:
  deadline: 5m
  skip-dirs:
    - vendor/.*
  skip-files:
    # ignore K8s specific object declaration
    - api/?.*/groupversion_info.go
    - api/?.*/object_.*.go

# [v1.45.2] https://golangci-lint.run/usage/configuration/
linters-settings:

  cyclop:
    max-complexity: 30

  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - github.com/davecgh/go-spew/spew

  dupl:
    threshold: 500

  errcheck:
    check-type-assertions: true

  forbidigo:
    forbid:
      - ^print\.*$

  funlen:
    lines: 240
    statements: 160

  gci:
    sections:
      - standard
      - default
      - prefix(code.local)

  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - whyNoLint

  gosec:
    excludes:
      - G401 # Use of weak cryptographic primitive
      - G501 # Blocklisted import crypto/md5: weak cryptographic primitive
      - G505 # Blocklisted import crypto/sha1: weak cryptographic primitive

  govet:
    check-shadowing: true
    enable-all: true

  ireturn:
    allow:
      - error
      - stdlib
      - dynamic.Interface # K8s
      - cache.SharedIndexInformer # K8s

  lll:
    line-length: 200

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true

  prealloc:
    for-loops: true

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel
        yaml: goCamel

  varnamelen:
    max-distance: 6
    min-name-length: 2
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *foo.Bar
      - e error
      - i int
      - const C
      - T any
      - m map[string]int

# [v1.1.4] https://github.com/mgechev/revive/tree/v1.1.4#available-rules
  revive:
    severity: warning
    rules:
#      - name: add-constant
      - name: argument-limit
        arguments: 9
      - name: atomic
      - name: banned-characters
        arguments: ["Ω","Σ","σ"]
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
#      - name: cognitive-complexity
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
#      - name: cyclomatic
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
#      - name: file-header
      - name: flag-parameter
#      - name: function-length
      - name: function-result-limit
        arguments: 4
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: imports-blacklist
      - name: increment-decrement
      - name: indent-error-flow
#      - name: line-length-limit
#      - name: max-public-structs
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: optimize-operands-order
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: range-val-in-closure
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-format
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
        arguments: ["fmt.Printf", "fmt.Println", "fmt.Print"]
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: useless-break
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value

linters:
  disable-all: true
  # disable: # DEPRECATED
  #  - golint
  #  - interfacer
  #  - maligned
  #  - scopelint
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
#    - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
#    - gocognit
    - goconst
    - gocritic
#    - gocyclo
    - godot
    - godox
#    - goerr113
#    - gofmt
    - gofumpt
#    - goheader
    - goimports
    - gomnd
#    - gomoddirectives
#    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
#    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
#    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
